import 'package:park_with_conscience/model/home_screen_categories.dart';
import 'package:park_with_conscience/screens/categoryScreen.dart';
List<Details> categories = [ 
  Details( 
    name: "Smart Solar Lights", 
    imageAddress: "assets/images/solarLights.jpeg", 
    screenName: CategoryScreen(
      title: 'Solar Lights', 
      imagePath: 'assets/gifs/solarLights.gif', 
      aboutContent: 
      """Ultra Bright and Motion Sensor Solar light: 
      
With 40 reflective LED in 3 sides, it can provide way brighter and wider outdoor lighting for places in the garden and detect motion up to 17 feet within angle of 120 degrees. The Sensitive Motion Inductor can detect the slightest motion.
      
There are three optional lighting modes for your choice: 

1.Security Mode (Motion sensor light turns on for 25 seconds when it detects movements and turns off automatically) 

2.Dimmable Sensor Control (Motion light turns on in dim mode at night and brightens for 25 seconds when it detects motion) 

3.Always On Mode (It turns on at night and stays medium light with or without detecting motion)

Challenges:
You have to find the ideal place with enough sunlight.
We placed the light after carefully examining the whole area and finding the ideal place on a tree.
""", 
    ) 
  ), 
  Details( 
    name: "Sprinklers", 
    imageAddress: "assets/images/sprinklers.png", 
    screenName: CategoryScreen(
      title: 'Sprinklers', 
      imagePath: 'assets/gifs/sprinkler.gif',
      aboutContent: """Water sprinkler 

The high-quality adjustable spray arms with 4 forms nozzle can adjust the sprinkling angle to 45 degrees or 90 degrees to achieve large-area watering effects, or to achieve higher density watering effects.

There are 3 kinds of sprinklers:
1 90 degree sprinkler
2 180 degree sprinkler
3 360 degree sprinkler

We selected the 90 degree sprinkler based on our needs.

Challenges:
The sprinklers need to be regularly used else they would become blocked with algae.
""", 
      ) 
  ), 
  Details( 
    name: "Free Nursery", 
    imageAddress: "assets/images/nursery.heic", 
    screenName: CategoryScreen(
      title: 'Free Nursery', 
      imagePath: 'assets/gifs/nursery.gif',
      aboutContent: """Free Nursery in park

The park offers free plants to all. Anybody and Everybody is free to take any plant from the nursery provided inside the park.

The Saplings are taken from the park itself and grown inside the park as well. This makes this nursery self-sustainable with minimal maintainance and truly free.

The plants in the nursery are also grown from existing plants through various techniques.

The milk packets or any plastic containers that are usually thrown away on roads or that end up in garbage dump are utilized here as containers for the plants.
This way this nursery also solves the problem of wastage and littering to some extent.

""", 
      ) 
  ), 
  Details( 
    name: "Entry Gates", 
    imageAddress: "assets/images/gate.jpeg", 
    screenName: CategoryScreen(
      title: 'Automatic Closing Gate', 
      imagePath: 'assets/gifs/gate.gif',
      aboutContent:"""Gates at all four sides of park.

The park is equipped with automatic closing gates on all four sides.
Door Stoppers are used to implement this functionality.

This solves the problem of stray animals getting inside the park. 
As these gates open outside of park, thus requiring to pull the gates and close automatically afterwards.




""", 
      )
  ), 
  Details( 
    name: "Drainage", 
    imageAddress: "assets/images/drainage.jpeg", 
    screenName: CategoryScreen(
      title: 'Drainage', 
      imagePath: 'assets/gifs/drainage.gif',
      aboutContent:"""Drainage pipe on park's boundary

There are drainage pipes on parks boundary wall with provide a pathway to drain the water on roads into the park.

In rainy season, The streets are filled with water and the sewarage gets blocked. In that time these pipes provide a path to water to flow into the park.

This solves two problems:
1. It recharges the Ground Water level and provides water to plants in the park.
2. It Keeps the streets clean and prevents water clogs.

""", 
      )
  ), 
  Details( 
    name: "Compost pit", 
    imageAddress: "assets/images/compostPit.jpeg", 
    screenName: CategoryScreen(
      title: 'Compost pit', 
      imagePath: 'assets/gifs/compostPit.gif',
      aboutContent: """Compost pit inside park

A compost pit is built inside the park. 
People from the neighbourhood throw all their organic waste into the pit and after a span of 2 months it gets converted to compost.

The first thing that comes in mind when thinking about compost pit is the smell that is generated by it.
But we have solved that problem here. The smell is generated when any of the three factors is not in required amount.
1. Oxygen
2. Sunlight
3. Water

Here's how we have addressed that issue:
1. The pit has large holes on the sides that allow air to pass through even at the bottom of the pit. This ensures that enough air is provided to the compost.
2. The pit is constructed in such a place where it recieves adequate sunlight which helps the process.
3. Water is provided in sufficient quantity, to keep the compost moist and not wet. This ensures that the bacteria have sufficient water.

This way the compost pit is naturally kept smell free and generates enough compost for the whole park.

The pit is divided into 3 parts. 
One part is filled at a time and when it fills to the top, the pit is covered from the top for 2-3 months to give it enough time to convert into compost.
The second and third pit is filled in the meantime, thus ensuring that compost is created continuously and an empty pit is present.

""", 
      ) 
  ), 
  
];